### ISSUE TITLE
Créer une vue pour le menu principal

### ISSUE THREAD

**Issue by victorlevasseur** [victorlevasseur/Jeu-du-menhir#50]

**Comment by zer0tonin** [comment]
- [x] v1 : interface créé
- [] v2 : contrôleur créé
- [] v3 : implémentation de la méthode update (nécessite d'avoir fini les modifications de Partie)

(Pas sûr que la v3 soit nécessaire)

**Comment by victorlevasseur** [comment]
~~Je pense que les événéments des vues doivent être géré à l'intérieur de la vue qui doit ensuite appeler une méthode du controlleur en lui passant tout ce qui est nécessaire car le controlleur n'est pas censé connaître la/les vue(s) (or c'est le cas car tu réimplémentes `ActionListener` dans le controlleur et tu utilises la vue à l'intérieur : du coup, pas possible de mettre une autre vue à la place sans changer le code du controlleur).~~

**Comment by victorlevasseur** [comment]
~~Ou alors, on peut regrouper la vue et le controlleur ensemble, histoire d'avoir un simple système Observeur/Observable qui serait plus simple et tout autant fonctionnel (apparamment, on est autorisé à faire un MVC avec vue et controlleur ensembles).~~

**Comment by victorlevasseur** [comment]
Je viens de lire quelques doc sur Internet, **c'est bon comme tu as fait**. Désolé !
