### ISSUE TITLE
Créer une vue pour le jeu

### ISSUE THREAD

**Issue by victorlevasseur** [victorlevasseur/Jeu-du-menhir#51]
Contient : 
- une zone affichant un historique des actions
- le numéro de la manche
- la liste des joueurs dans leur ordre de jeu (dans la manche courante) et le joueur qui joue actuellement (et leur score totale en partie avancée)
- la main du joueur physique (via une vue intégrée)
- la main des autres joueurs (uniquement les menhirs et graines, pas les cartes, via une vue intégrée)

**Comment by zer0tonin** [comment]
L'historique des actions c'est très très facultatif ça.

**Comment by victorlevasseur** [comment]
J'imaginais une zone qui affiche ce que s'est passé. Juste sous forme d'une
zone de texte à laquelle on ajoute des lignes au fur et à mesure. Mais
c'est pas une priorité.

Le jeu. 31 déc. 2015 à 18:09, ElDawgerino notifications@github.com a
écrit :
