### ISSUE TITLE
Créer une vue pour la main du joueur

### ISSUE THREAD

**Issue by victorlevasseur** [victorlevasseur/Jeu-du-menhir#52]
Une vue qui affiche : 
- le nombre de menhirs, de graines
- les cartes (si souhaité : pas pour la vue des mains des autres joueurs)

**Comment by zer0tonin** [comment]
Est-ce nécessairement séparé de la vue du jeu?

**Comment by victorlevasseur** [comment]
Oui, on peut ainsi la disposer plusieurs fois sur la vue du jeu (pour les mains de tous les joueurs).

**Comment by zer0tonin** [comment]
Dans ce cas il faudrait peut être une vue différente pour la vue des IA et du joueur parce que je ne crois pas que le joueur soit censé voir les cartes de ces adversaires.

Edit : j'ai rien dit tu l'as déjà marqué.

**Comment by victorlevasseur** [comment]
Si, elle est intégrée dans celle du jeu. Mais cela ne l'empêche pas d'être une classe différente pour autant. Un booléen peut permettre de dire si l'on veut voir les cartes de la main ou non (pour les IA). Dans tous les cas, il faut voir les menhirs et les graines.

**Comment by zer0tonin** [comment]
On prend pas les images des cartes, on met juste le texte?

**Comment by victorlevasseur** [comment]
Comme tu veux

Le mer. 30 déc. 2015 à 14:26, ElDawgerino notifications@github.com a
écrit :
